#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/configure_go2_rssi_sudoers.sh [project_dir]

Run this once on the Go2 computer. It creates a narrow sudoers rule so the
remote RSSI collector can run from non-interactive SSH without asking for a
password. It does not grant NOPASSWD: ALL.

Example:
  cd /home/unitree/rssi_go2
  scripts/configure_go2_rssi_sudoers.sh /home/unitree/rssi_go2
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

project_dir="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
user_name="$(id -un)"
sudoers_file="/etc/sudoers.d/go2-rssi-${user_name}"

find_cmd() {
  local name="$1"
  local path
  path="$(type -P "$name" 2>/dev/null || true)"
  if [[ -z "$path" || ! -x "$path" ]]; then
    echo "Missing executable command: $name" >&2
    exit 1
  fi
  printf '%s\n' "$path"
}

btattach_bin="$(find_cmd btattach)"
hciconfig_bin="$(find_cmd hciconfig)"
hcitool_bin="$(find_cmd hcitool)"
kill_bin="$(find_cmd kill)"
chown_bin="$(find_cmd chown)"

rssi_binaries=()
for candidate in \
  "$project_dir/build_rssi/test_rssi" \
  "$project_dir/test_rssi" \
  "$project_dir/bt_migrate_pack/test_rssi"; do
  if [[ -x "$candidate" ]]; then
    rssi_binaries+=("$candidate")
  fi
done

if [[ "${#rssi_binaries[@]}" -eq 0 ]]; then
  echo "Missing executable RSSI binary. Build it with scripts/build_rssi_logger.sh" >&2
  exit 1
fi

required_paths=("${rssi_binaries[@]}")

for path in "${required_paths[@]}"; do
  if [[ ! -x "$path" ]]; then
    echo "Missing executable required for sudoers rule: $path" >&2
    exit 1
  fi
done

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Generated by RobotRSSI scripts/configure_go2_rssi_sudoers.sh"
  echo "# Allows non-interactive remote RSSI collection only."
  echo "Cmnd_Alias GO2_RSSI_BTATTACH = $btattach_bin -B /dev/ttyACM* -S *"
  echo "Cmnd_Alias GO2_RSSI_HCICONFIG = $hciconfig_bin hci* up"
  echo "Cmnd_Alias GO2_RSSI_HCITOOL = $hcitool_bin -i hci* cmd *"
  printf 'Cmnd_Alias GO2_RSSI_BIN = '
  local_sep=""
  for binary in "${rssi_binaries[@]}"; do
    printf '%s%s *' "$local_sep" "$binary"
    local_sep=", "
  done
  printf '\n'
  echo "Cmnd_Alias GO2_RSSI_CLEANUP = $kill_bin *, $chown_bin -R *"
  echo "$user_name ALL=(root) NOPASSWD: GO2_RSSI_BTATTACH, GO2_RSSI_HCICONFIG, GO2_RSSI_HCITOOL, GO2_RSSI_BIN, GO2_RSSI_CLEANUP"
} >"$tmp_file"

sudo visudo -cf "$tmp_file"
sudo install -o root -g root -m 0440 "$tmp_file" "$sudoers_file"

echo "Installed sudoers rule: $sudoers_file"
echo "Verify with:"
echo "  sudo -n $hcitool_bin -i hci0 cmd 0x03 0x0003"
