#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/go2_robot_replay_route.sh <route_file> [output_csv]

Run this on the Go2 computer. It replays a route generated by
scripts/go2_process_route_capture.sh using only Unitree SDK data and Move().

Environment:
  IFACE              Unitree network interface. Defaults to eth0.
  XY_TOLERANCE_M     Defaults to 0.25.
  MAX_VX_MPS         Defaults to 0.30.
  MAX_VY_MPS         Defaults to 0.08.
  MAX_WZ_RADPS       Defaults to 0.45.
  YAW_TOLERANCE_RAD  Final heading tolerance. Defaults to 0.35.
  TIMEOUT_SEC        Defaults to 90.
  MOTION_CLIENT      obstacles_avoid or sport. Defaults to obstacles_avoid.
  CONTROL_HZ         Defaults to 20.
  PROJECT_ROOT       Defaults to the parent of this scripts directory.
EOF
}

if [[ $# -lt 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 1
fi

route_file="$(realpath "$1")"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="${PROJECT_ROOT:-$(cd "$script_dir/.." && pwd)}"
exe="$project_root/unitree_sdk2/build_go2/bin/go2_route_replay"
if [[ ! -x "$exe" ]]; then
  exe="$project_root/unitree_sdk2/build_go2/example/go2/go2_route_replay"
fi
if [[ ! -x "$exe" ]]; then
  echo "go2_route_replay not built. Build unitree_sdk2 first." >&2
  exit 2
fi

timestamp="$(date +%Y%m%d_%H%M%S)"
output_csv="${2:-$HOME/go2_route_replays/replay_${timestamp}.csv}"
mkdir -p "$(dirname "$output_csv")"

sdk_arch="$(uname -m)"
sdk_library_path=""
for lib_dir in \
  "$project_root/unitree_sdk2/thirdparty/lib/$sdk_arch" \
  "$project_root/unitree_sdk2/lib/$sdk_arch"; do
  if [[ -d "$lib_dir" ]]; then
    if [[ -z "$sdk_library_path" ]]; then
      sdk_library_path="$lib_dir"
    else
      sdk_library_path="$sdk_library_path:$lib_dir"
    fi
  fi
done
if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
  sdk_library_path="${sdk_library_path:+$sdk_library_path:}${LD_LIBRARY_PATH}"
fi

echo "Go2 route replay:"
echo "  route_file:      $route_file"
echo "  output_csv:      $output_csv"
echo "  iface:           ${IFACE:-eth0}"
echo "  xy_tolerance_m:  ${XY_TOLERANCE_M:-0.25}"
echo "  yaw_tolerance:   ${YAW_TOLERANCE_RAD:-0.35}"
echo "  motion_client:   ${MOTION_CLIENT:-obstacles_avoid}"
echo

exec env LD_LIBRARY_PATH="$sdk_library_path" "$exe" \
  "${IFACE:-eth0}" \
  "$route_file" \
  "$output_csv" \
  "${XY_TOLERANCE_M:-0.25}" \
  "${MAX_VX_MPS:-0.30}" \
  "${MAX_VY_MPS:-0.08}" \
  "${MAX_WZ_RADPS:-0.45}" \
  "${TIMEOUT_SEC:-90}" \
  "${MOTION_CLIENT:-obstacles_avoid}" \
  "${CONTROL_HZ:-20}" \
  "${YAW_TOLERANCE_RAD:-0.35}"
